[versions]
kotlinJvm = "2.3.20"
shadow = "9.4.1"
resourceFactoryPaper = "1.3.1"
paperweightUserdev = "2.0.0-beta.21"

[plugins]
kotlin-jvm = { id = "org.jetbrains.kotlin.jvm", version.ref = "kotlinJvm" }
shadow = { id = "com.gradleup.shadow", version.ref = "shadow" }
resource-factory-paper = { id = "xyz.jpenilla.resource-factory-paper-convention", version.ref = "resourceFactoryPaper" }
paperweight-userdev = { id = "io.papermc.paperweight.userdev", version.ref = "paperweightUserdev" }
